// Class: ReadCuts
// Automatically generated by MethodBase::MakeClass
//

/* configuration options =====================================================

#GEN -*-*-*-*-*-*-*-*-*-*-*- general info -*-*-*-*-*-*-*-*-*-*-*-

Method         : Cuts::Cuts
TMVA Release   : 4.2.1         [262657]
ROOT Release   : 6.04/18       [394258]
Creator        : jogurt
Date           : Sun Apr  9 20:31:23 2017
Host           : Linux jogurt-UX32VD 4.4.0-38-generic #57~14.04.1-Ubuntu SMP Tue Sep 6 17:20:43 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Dir            : /home/jogurt/Study/Particles/Bfinder
Training events: 47723
Analysis type  : [Classification]


#OPT -*-*-*-*-*-*-*-*-*-*-*-*- options -*-*-*-*-*-*-*-*-*-*-*-*-

# Set by User:
V: "False" [Verbose output (short form of "VerbosityLevel" below - overrides the latter one)]
H: "True" [Print method-specific help message]
FitMethod: "MC" [Minimisation Method (GA, SA, and MC are the primary methods to be used; the others have been introduced for testing purposes and are depreciated)]
EffMethod: "EffSel" [Selection Method]
# Default:
VerbosityLevel: "Default" [Verbosity level]
VarTransform: "None" [List of variable transformations performed before training, e.g., "D_Background,P_Signal,G,N_AllClasses" for: "Decorrelation, PCA-transformation, Gaussianisation, Normalisation, each for the given class of events ('AllClasses' denotes all events of all classes, if no class indication is given, 'All' is assumed)"]
CreateMVAPdfs: "False" [Create PDFs for classifier outputs (signal and background)]
IgnoreNegWeightsInTraining: "False" [Events with negative weights are ignored in the training (but are included for testing and performance evaluation)]
CutRangeMin[0]: "-1.000000e+00" [Minimum of allowed cut range (set per variable)]
    CutRangeMin[1]: "-1.000000e+00"
    CutRangeMin[2]: "-1.000000e+00"
    CutRangeMin[3]: "-1.000000e+00"
    CutRangeMin[4]: "-1.000000e+00"
    CutRangeMin[5]: "-1.000000e+00"
    CutRangeMin[6]: "-1.000000e+00"
    CutRangeMin[7]: "-1.000000e+00"
    CutRangeMin[8]: "-1.000000e+00"
    CutRangeMin[9]: "-1.000000e+00"
    CutRangeMin[10]: "-1.000000e+00"
    CutRangeMin[11]: "-1.000000e+00"
    CutRangeMin[12]: "-1.000000e+00"
    CutRangeMin[13]: "-1.000000e+00"
    CutRangeMin[14]: "-1.000000e+00"
    CutRangeMin[15]: "-1.000000e+00"
    CutRangeMin[16]: "-1.000000e+00"
    CutRangeMin[17]: "-1.000000e+00"
    CutRangeMin[18]: "-1.000000e+00"
    CutRangeMin[19]: "-1.000000e+00"
    CutRangeMin[20]: "-1.000000e+00"
    CutRangeMin[21]: "-1.000000e+00"
    CutRangeMin[22]: "-1.000000e+00"
    CutRangeMin[23]: "-1.000000e+00"
    CutRangeMin[24]: "-1.000000e+00"
    CutRangeMin[25]: "-1.000000e+00"
    CutRangeMin[26]: "-1.000000e+00"
    CutRangeMin[27]: "-1.000000e+00"
    CutRangeMin[28]: "-1.000000e+00"
    CutRangeMin[29]: "-1.000000e+00"
CutRangeMax[0]: "-1.000000e+00" [Maximum of allowed cut range (set per variable)]
    CutRangeMax[1]: "-1.000000e+00"
    CutRangeMax[2]: "-1.000000e+00"
    CutRangeMax[3]: "-1.000000e+00"
    CutRangeMax[4]: "-1.000000e+00"
    CutRangeMax[5]: "-1.000000e+00"
    CutRangeMax[6]: "-1.000000e+00"
    CutRangeMax[7]: "-1.000000e+00"
    CutRangeMax[8]: "-1.000000e+00"
    CutRangeMax[9]: "-1.000000e+00"
    CutRangeMax[10]: "-1.000000e+00"
    CutRangeMax[11]: "-1.000000e+00"
    CutRangeMax[12]: "-1.000000e+00"
    CutRangeMax[13]: "-1.000000e+00"
    CutRangeMax[14]: "-1.000000e+00"
    CutRangeMax[15]: "-1.000000e+00"
    CutRangeMax[16]: "-1.000000e+00"
    CutRangeMax[17]: "-1.000000e+00"
    CutRangeMax[18]: "-1.000000e+00"
    CutRangeMax[19]: "-1.000000e+00"
    CutRangeMax[20]: "-1.000000e+00"
    CutRangeMax[21]: "-1.000000e+00"
    CutRangeMax[22]: "-1.000000e+00"
    CutRangeMax[23]: "-1.000000e+00"
    CutRangeMax[24]: "-1.000000e+00"
    CutRangeMax[25]: "-1.000000e+00"
    CutRangeMax[26]: "-1.000000e+00"
    CutRangeMax[27]: "-1.000000e+00"
    CutRangeMax[28]: "-1.000000e+00"
    CutRangeMax[29]: "-1.000000e+00"
VarProp[0]: "FSmart" [Categorisation of cuts]
    VarProp[1]: "FSmart"
    VarProp[2]: "FSmart"
    VarProp[3]: "FSmart"
    VarProp[4]: "FSmart"
    VarProp[5]: "FSmart"
    VarProp[6]: "FSmart"
    VarProp[7]: "FSmart"
    VarProp[8]: "FSmart"
    VarProp[9]: "FSmart"
    VarProp[10]: "FSmart"
    VarProp[11]: "FSmart"
    VarProp[12]: "FSmart"
    VarProp[13]: "FSmart"
    VarProp[14]: "FSmart"
    VarProp[15]: "FSmart"
    VarProp[16]: "FSmart"
    VarProp[17]: "FSmart"
    VarProp[18]: "FSmart"
    VarProp[19]: "FSmart"
    VarProp[20]: "FSmart"
    VarProp[21]: "FSmart"
    VarProp[22]: "FSmart"
    VarProp[23]: "FSmart"
    VarProp[24]: "FSmart"
    VarProp[25]: "FSmart"
    VarProp[26]: "FSmart"
    VarProp[27]: "FSmart"
    VarProp[28]: "FSmart"
    VarProp[29]: "FSmart"
##


#VAR -*-*-*-*-*-*-*-*-*-*-*-* variables *-*-*-*-*-*-*-*-*-*-*-*-

NVar 30
kaonP_pt_0c                   kaonP_pt_0c                   kaonP_pt_0c                   kaonP_pt_0c                                                     'F'    [0.700005173683,33.6804733276]
kaonP_track_normchi2          kaonP_track_normchi2          kaonP_track_normchi2          kaonP_track_normchi2                                            'F'    [2.30861047612e-07,12.2663011551]
kaonP_Hits                    kaonP_Hits                    kaonP_Hits                    kaonP_Hits                                                      'F'    [3,47]
kaonP_NTrackerLayers          kaonP_NTrackerLayers          kaonP_NTrackerLayers          kaonP_NTrackerLayers                                            'F'    [3,17]
kaonP_dxy_Bsdecay             kaonP_dxy_Bsdecay             kaonP_dxy_Bsdecay             kaonP_dxy_Bsdecay                                               'F'    [-1.59642744064,2.3189303875]
kaonM_pt_0c                   kaonM_pt_0c                   kaonM_pt_0c                   kaonM_pt_0c                                                     'F'    [0.700053215027,39.7238731384]
kaonM_track_normchi2          kaonM_track_normchi2          kaonM_track_normchi2          kaonM_track_normchi2                                            'F'    [1.55092664045e-07,14.0269851685]
kaonM_Hits                    kaonM_Hits                    kaonM_Hits                    kaonM_Hits                                                      'F'    [3,35]
kaonM_NTrackerLayers          kaonM_NTrackerLayers          kaonM_NTrackerLayers          kaonM_NTrackerLayers                                            'F'    [3,17]
kaonM_dxy_Bsdecay             kaonM_dxy_Bsdecay             kaonM_dxy_Bsdecay             kaonM_dxy_Bsdecay                                               'F'    [-2.48894810677,1.89954280853]
deltaR_KpKm                   deltaR_KpKm                   deltaR_KpKm                   deltaR_KpKm                                                     'F'    [0.000771605293266,0.407067805529]
phi_pt_0c                     phi_pt_0c                     phi_pt_0c                     phi_pt_0c                                                       'F'    [1.37941670418,73.4042434692]
Bs_pt_Cjp                     Bs_pt_Cjp                     Bs_pt_Cjp                     Bs_pt_Cjp                                                       'F'    [8.86978435516,135.369674683]
Bs_bcvtxDS2d_Cjp              Bs_bcvtxDS2d_Cjp              Bs_bcvtxDS2d_Cjp              Bs_bcvtxDS2d_Cjp                                                'F'    [0.000573473749682,180.564498901]
BsVtx_Chi2                    BsVtx_Chi2                    BsVtx_Chi2                    BsVtx_Chi2                                                      'F'    [0.0245882682502,16.8097743988]
Bs_bcvtx_cos2_Cjp             Bs_bcvtx_cos2_Cjp             Bs_bcvtx_cos2_Cjp             Bs_bcvtx_cos2_Cjp                                               'F'    [0.904097855091,1]
Bs_Bcdecay_weight             Bs_Bcdecay_weight             Bs_Bcdecay_weight             Bs_Bcdecay_weight                                               'F'    [0.831372559071,0.984313726425]
Bs_Eta_cjp                    Bs_Eta_cjp                    Bs_Eta_cjp                    Bs_Eta_cjp                                                      'F'    [-2.17133951187,2.23718333244]
Bs_Phi_cjp                    Bs_Phi_cjp                    Bs_Phi_cjp                    Bs_Phi_cjp                                                      'F'    [-3.14154148102,3.14135408401]
pion_pt_0c                    pion_pt_0c                    pion_pt_0c                    pion_pt_0c                                                      'F'    [0.400005340576,26.5166053772]
pion_track_normchi2           pion_track_normchi2           pion_track_normchi2           pion_track_normchi2                                             'F'    [5.38284972151e-08,61.4913597107]
pion_Hits                     pion_Hits                     pion_Hits                     pion_Hits                                                       'F'    [3,63]
pion_NTrackerLayers           pion_NTrackerLayers           pion_NTrackerLayers           pion_NTrackerLayers                                             'F'    [3,20]
pion_dxy_Bcdecay              pion_dxy_Bcdecay              pion_dxy_Bcdecay              pion_dxy_Bcdecay                                                'F'    [-1.46129345894,1.81426525116]
pion_Bcdecay_weight           pion_Bcdecay_weight           pion_Bcdecay_weight           pion_Bcdecay_weight                                             'F'    [0.752941191196,0.984313726425]
Bc_pt                         Bc_pt                         Bc_pt                         Bc_pt                                                           'F'    [8.9657907486,145.238372803]
Bc_pvDS2d                     Bc_pvDS2d                     Bc_pvDS2d                     Bc_pvDS2d                                                       'F'    [0.000441214506282,21.5012454987]
Bc_pvcos2                     Bc_pvcos2                     Bc_pvcos2                     Bc_pvcos2                                                       'F'    [0.900003373623,1]
Bc_Eta                        Bc_Eta                        Bc_Eta                        Bc_Eta                                                          'F'    [-2.16885948181,2.26399803162]
Bc_Phi                        Bc_Phi                        Bc_Phi                        Bc_Phi                                                          'F'    [-3.14128470421,3.1415002346]
NSpec 0


============================================================================ */

#include <vector>
#include <cmath>
#include <string>
#include <iostream>

#ifndef IClassifierReader__def
#define IClassifierReader__def

class IClassifierReader {

 public:

   // constructor
   IClassifierReader() : fStatusIsClean( true ) {}
   virtual ~IClassifierReader() {}

   // return classifier response
   virtual double GetMvaValue( const std::vector<double>& inputValues ) const = 0;

   // returns classifier status
   bool IsStatusClean() const { return fStatusIsClean; }

 protected:

   bool fStatusIsClean;
};

#endif

class ReadCuts : public IClassifierReader {

 public:

   // constructor
   ReadCuts( std::vector<std::string>& theInputVars ) 
      : IClassifierReader(),
        fClassName( "ReadCuts" ),
        fNvars( 30 ),
        fIsNormalised( false )
   {      
      // the training input variables
      const char* inputVars[] = { "kaonP_pt_0c", "kaonP_track_normchi2", "kaonP_Hits", "kaonP_NTrackerLayers", "kaonP_dxy_Bsdecay", "kaonM_pt_0c", "kaonM_track_normchi2", "kaonM_Hits", "kaonM_NTrackerLayers", "kaonM_dxy_Bsdecay", "deltaR_KpKm", "phi_pt_0c", "Bs_pt_Cjp", "Bs_bcvtxDS2d_Cjp", "BsVtx_Chi2", "Bs_bcvtx_cos2_Cjp", "Bs_Bcdecay_weight", "Bs_Eta_cjp", "Bs_Phi_cjp", "pion_pt_0c", "pion_track_normchi2", "pion_Hits", "pion_NTrackerLayers", "pion_dxy_Bcdecay", "pion_Bcdecay_weight", "Bc_pt", "Bc_pvDS2d", "Bc_pvcos2", "Bc_Eta", "Bc_Phi" };

      // sanity checks
      if (theInputVars.size() <= 0) {
         std::cout << "Problem in class \"" << fClassName << "\": empty input vector" << std::endl;
         fStatusIsClean = false;
      }

      if (theInputVars.size() != fNvars) {
         std::cout << "Problem in class \"" << fClassName << "\": mismatch in number of input values: "
                   << theInputVars.size() << " != " << fNvars << std::endl;
         fStatusIsClean = false;
      }

      // validate input variables
      for (size_t ivar = 0; ivar < theInputVars.size(); ivar++) {
         if (theInputVars[ivar] != inputVars[ivar]) {
            std::cout << "Problem in class \"" << fClassName << "\": mismatch in input variable names" << std::endl
                      << " for variable [" << ivar << "]: " << theInputVars[ivar].c_str() << " != " << inputVars[ivar] << std::endl;
            fStatusIsClean = false;
         }
      }

      // initialize min and max vectors (for normalisation)
      fVmin[0] = 0;
      fVmax[0] = 0;
      fVmin[1] = 0;
      fVmax[1] = 0;
      fVmin[2] = 0;
      fVmax[2] = 0;
      fVmin[3] = 0;
      fVmax[3] = 0;
      fVmin[4] = 0;
      fVmax[4] = 0;
      fVmin[5] = 0;
      fVmax[5] = 0;
      fVmin[6] = 0;
      fVmax[6] = 0;
      fVmin[7] = 0;
      fVmax[7] = 0;
      fVmin[8] = 0;
      fVmax[8] = 0;
      fVmin[9] = 0;
      fVmax[9] = 0;
      fVmin[10] = 0;
      fVmax[10] = 0;
      fVmin[11] = 0;
      fVmax[11] = 0;
      fVmin[12] = 0;
      fVmax[12] = 0;
      fVmin[13] = 0;
      fVmax[13] = 0;
      fVmin[14] = 0;
      fVmax[14] = 0;
      fVmin[15] = 0;
      fVmax[15] = 0;
      fVmin[16] = 0;
      fVmax[16] = 0;
      fVmin[17] = 0;
      fVmax[17] = 0;
      fVmin[18] = 0;
      fVmax[18] = 0;
      fVmin[19] = 0;
      fVmax[19] = 0;
      fVmin[20] = 0;
      fVmax[20] = 0;
      fVmin[21] = 0;
      fVmax[21] = 0;
      fVmin[22] = 0;
      fVmax[22] = 0;
      fVmin[23] = 0;
      fVmax[23] = 0;
      fVmin[24] = 0;
      fVmax[24] = 0;
      fVmin[25] = 0;
      fVmax[25] = 0;
      fVmin[26] = 0;
      fVmax[26] = 0;
      fVmin[27] = 0;
      fVmax[27] = 0;
      fVmin[28] = 0;
      fVmax[28] = 0;
      fVmin[29] = 0;
      fVmax[29] = 0;

      // initialize input variable types
      fType[0] = 'F';
      fType[1] = 'F';
      fType[2] = 'F';
      fType[3] = 'F';
      fType[4] = 'F';
      fType[5] = 'F';
      fType[6] = 'F';
      fType[7] = 'F';
      fType[8] = 'F';
      fType[9] = 'F';
      fType[10] = 'F';
      fType[11] = 'F';
      fType[12] = 'F';
      fType[13] = 'F';
      fType[14] = 'F';
      fType[15] = 'F';
      fType[16] = 'F';
      fType[17] = 'F';
      fType[18] = 'F';
      fType[19] = 'F';
      fType[20] = 'F';
      fType[21] = 'F';
      fType[22] = 'F';
      fType[23] = 'F';
      fType[24] = 'F';
      fType[25] = 'F';
      fType[26] = 'F';
      fType[27] = 'F';
      fType[28] = 'F';
      fType[29] = 'F';

      // initialize constants
      Initialize();

   }

   // destructor
   virtual ~ReadCuts() {
      Clear(); // method-specific
   }

   // the classifier response
   // "inputValues" is a vector of input values in the same order as the 
   // variables given to the constructor
   double GetMvaValue( const std::vector<double>& inputValues ) const;

 private:

   // method-specific destructor
   void Clear();

   // common member variables
   const char* fClassName;

   const size_t fNvars;
   size_t GetNvar()           const { return fNvars; }
   char   GetType( int ivar ) const { return fType[ivar]; }

   // normalisation of input variables
   const bool fIsNormalised;
   bool IsNormalised() const { return fIsNormalised; }
   double fVmin[30];
   double fVmax[30];
   double NormVariable( double x, double xmin, double xmax ) const {
      // normalise to output range: [-1, 1]
      return 2*(x - xmin)/(xmax - xmin) - 1.0;
   }

   // type of input variable: 'F' or 'I'
   char   fType[30];

   // initialize internal variables
   void Initialize();
   double GetMvaValue__( const std::vector<double>& inputValues ) const;

   // private members (method specific)
   // not implemented for class: "ReadCuts"
};
   inline double ReadCuts::GetMvaValue( const std::vector<double>& inputValues ) const
   {
      // classifier response value
      double retval = 0;

      // classifier response, sanity check first
      if (!IsStatusClean()) {
         std::cout << "Problem in class \"" << fClassName << "\": cannot return classifier response"
                   << " because status is dirty" << std::endl;
         retval = 0;
      }
      else {
         if (IsNormalised()) {
            // normalise variables
            std::vector<double> iV;
            iV.reserve(inputValues.size());
            int ivar = 0;
            for (std::vector<double>::const_iterator varIt = inputValues.begin();
                 varIt != inputValues.end(); varIt++, ivar++) {
               iV.push_back(NormVariable( *varIt, fVmin[ivar], fVmax[ivar] ));
            }
            retval = GetMvaValue__( iV );
         }
         else {
            retval = GetMvaValue__( inputValues );
         }
      }

      return retval;
   }
